# Site
name: "Gniliy"
title: "Gniliy"
description: "Gniliy's Blog. Let's go!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
# mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: tba@corp.com

# Authors
authors:
  gniliy:
    name: Gniliy
    display_name: Gniliy
    avatar: 'assets/images/avatar.png'
    email: tba@corp.com
    web: https://lawrenceh.github.io/
    description: "Author" 
  oay:
    name: Oay
    display_name: Oay

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-toc
    
# Archives
jekyll-archives:
  enabled:
    - categories
    - year
    - month
  layout: archive
  permalinks:
    category: '/category/:name/'
    year: '/:year/'
    month: '/:year/:month/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
   parse_block_html: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
